### ISSUE TITLE
PM09 Issues

### ISSUE THREAD

**Issue by jjgiesey** [Milligan-Engineering/HydroMan#3]
1. Keep header updated. (4)
2, Give pre and post condition for all functions (16) 
3. Do you want to append data? (85)
4. Update write file format (86)
5. Update read file format (97)
6. Be clear about date input format (280)
7. Take capital and small letter inputs.

**Comment by ruth0566** [comment]
fixed everything except for file formatting

**Comment by jjgiesey** [comment]
Issue closed. Remaining fixes put into stand alone issues.
