### ISSUE TITLE
Hydroman Issue

### ISSUE THREAD

**Issue by MackenzieSimpson** [Milligan-Engineering/HydroMan#4]
1.  Loops when using lower case letters instead of uppercase
2.  Loops when input is not S,D,W, or P.
3.  Loops when input is a number instead of S, D, W, or P.
4.  Date input is not specified so a correct date could be read as incorrect
5.  User profile worked good, but it reads the incorrect amount of water needed back 
6.  Amount of water in oz parameter needs fixing

**Comment by ruth0566** [comment]
fixed all errors
